### ISSUE TITLE
Upload Pictures

### ISSUE THREAD

**Issue by ivyapril** [lateralstudio/isycommunity#5]
When uploading more than one picture, single descriptions are needed 

example: uploading 10 pictures of baking a cake 
album description: here's the process/recipe of my chocolate cake
picture 1 description: this is what it will look like 
picture 2 description: first scramble eggs 
... 
so basically that the descriptions are not all the same on every picture 
hope that makes sense

**Comment by GuillaumeZuff** [comment]
Added a description field for each resource in the post edit popup. Will be available after the next update.
